# Generated by Django 6.0.2 on 2026-02-17 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straat', models.CharField(max_length=200)),
                ('nummer', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=20)),
                ('stad', models.CharField(max_length=200)),
                ('land', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
                ('kleur', models.CharField(blank=True, max_length=50, null=True)),
                ('btw_percentage', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bestelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('besteld_op', models.DateTimeField(auto_now_add=True)),
                ('leveradres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tac.adres')),
                ('productvariant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tac.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Levering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geleverd_op', models.DateTimeField(blank=True, null=True)),
                ('afleveradres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tac.adres')),
                ('bestelling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tac.bestelling')),
            ],
        ),
    ]
