# Generated by Django 6.0.2 on 2026-02-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Werknemer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=200)),
                ('achternaam', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Klant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=200)),
                ('achternaam', models.CharField(max_length=200)),
                ('adres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tac.adres')),
            ],
        ),
        migrations.AddField(
            model_name='bestelling',
            name='klant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tac.klant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tac.product'),
        ),
        migrations.AddField(
            model_name='bestelling',
            name='werknemer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tac.werknemer'),
        ),
    ]
